name: dotnet package

on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x', '5.0.x' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build with dotnet
        run: dotnet build --no-restore --output "BuildResults-${{ matrix.dotnet-version }}"
      - name: Upload dotnet build results
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-results-${{ matrix.dotnet-version }}
          path: BuildResults-${{ matrix.dotnet-version }}
        # Use always() to always run this step to publish build results when there are build failures
        if: ${{ always() }}